### ISSUE TITLE
Compilation on Ubuntu

### ISSUE THREAD

**Issue by 7890** [brummer10/Xputty#1]
Hi, the compilation fails on ubuntu with undefined symbols.
After putting `$(LDFLAGS)` to the end of the lines in examples/Makefile, it compiles fine.
```
        $(CC) simple-example.c ../xputty.c -o simple-example $(LDFLAGS)
        $(CC) example.c ../xputty.c -o example $(LDFLAGS)
        $(CC) example1.c ../xputty.c -o example1 $(LDFLAGS)
        $(CC) example2.c ../xputty.c -o example2 $(LDFLAGS)
```
Also: inline definition of loop counter (int i=0...) is only allowed in C99, simply putting int i; outside of the loop solved this for me.
Interesting tiny library! Thanks for sharing.

**Comment by 7890** [comment]
Nice

**Comment by brummer10** [comment]
Hi
thanks for reporting the issue.
I've pushed your fixes to the repository right now.

**Comment by 7890** [comment]
2 seconds time difference :)
